const path = require('path');
const Piscina = require('piscina');
const crypto = require('crypto');

const piscina = new Piscina({
  filename: path.resolve(__dirname, 'worker.js'),
});

const samples = [
  'Something',
  'Something Just Want I Know',
  'Something Something Just Want I know that',
  'Lorem ipsum dolor sit amet bla snej ejs edueyr',
  'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
  'Iaculis viverra placerat. Auctor ullamcorper justo, morbi neque. Dis taciti aliquet, convallis. Dictumst Elementum facilisi condimentum. Augue sociis natoque ultricies potenti rhoncus vivamus. Nostra nonummy per mollis sapien metus. Dui quam suspendisse.',
  `Quam dignissim pulvinar. Litora non hendrerit sit enim faucibus Tincidunt nulla tristique diam facilisi viverra cursus, hymenaeos curabitur nulla tortor elit taciti venenatis tempus volutpat augue hendrerit cubilia proin congue fringilla malesuada nunc. Vel gravida hac proin luctus donec mollis. Pretium dui. Ac lectus, aliquam taciti nascetur dapibus, ultrices dignissim inceptos interdum adipiscing etiam id Nisi ridiculus. Curabitur consequat primis mus eget, faucibus malesuada fringilla hymenaeos pharetra sociosqu netus. Eleifend. In feugiat in maecenas pellentesque posuere. Molestie turpis tempor pharetra duis vestibulum sodales viverra orci. Duis nonummy. Semper lacinia. Sagittis parturient molestie. Euismod tellus ac mattis quis vulputate. Lectus duis convallis mi massa suscipit interdum fusce tellus scelerisque. Egestas aliquam accumsan nibh lectus, enim, dui hac nostra imperdiet platea id venenatis vulputate. Euismod tristique neque lectus placerat, placerat dapibus Dignissim etiam arcu at rhoncus commodo feugiat fusce nisi lorem ut risus mi. Ultricies tincidunt egestas porttitor. Elit curae; habitasse porta conubia sagittis neque dis Lectus eleifend eleifend ante nibh dignissim neque metus. Nec proin lorem tristique hymenaeos. Mollis diam nascetur. In libero ultricies phasellus nibh rutrum facilisis suscipit inceptos, sociosqu malesuada porttitor ipsum tellus fringilla condimentum non. Aenean venenatis lobortis sollicitudin curae; eu nec congue. Sed luctus risus. Eget sociis risus nascetur lobortis duis diam orci sollicitudin tempus inceptos taciti dapibus iaculis morbi torquent mus neque hac primis mi fermentum porta sapien.

Taciti vel sed scelerisque hac ridiculus fusce, non dui donec sagittis Elementum volutpat turpis nisi amet, conubia potenti est rutrum condimentum Ornare adipiscing etiam nisi aliquam in augue nonummy odio a nostra. Adipiscing risus lacinia. Nec habitasse consectetuer torquent suspendisse montes ultricies ultricies nonummy viverra. Diam at aliquet faucibus platea pede tortor viverra ullamcorper eu pellentesque orci nullam arcu pede neque luctus facilisis magnis consectetuer varius fames. Praesent mollis tincidunt montes suscipit leo commodo lacinia. Quam auctor magnis. Lorem neque curae; class morbi nunc turpis diam nonummy vestibulum nibh erat sollicitudin potenti diam convallis vehicula Donec ornare turpis platea pulvinar etiam senectus, odio primis cum accumsan lectus class vestibulum habitasse. Nisl congue commodo sociosqu venenatis habitant ligula luctus pulvinar quam at habitasse. Velit. Varius sed ac blandit. Dapibus cras Sociis mattis lacinia vitae auctor eu nisi nibh posuere blandit eros tincidunt Commodo accumsan aliquet sociosqu sociis sagittis fringilla dis odio aptent inceptos. Integer placerat purus, sapien elit quam aliquet. A a pharetra dolor iaculis nam vel faucibus magnis, suspendisse. Pulvinar cubilia dis hendrerit class hendrerit dolor. Donec Cubilia vestibulum dis hac nulla. Mauris lorem netus molestie. Mollis. Potenti eleifend bibendum leo, laoreet consequat inceptos duis ornare nonummy ligula, lobortis conubia augue, dictum erat turpis quis pede sem pharetra Porta. Interdum. Euismod facilisi ornare aptent Porta sociosqu sapien urna hac lorem erat, cum accumsan felis leo cras curabitur habitasse enim hymenaeos iaculis per velit placerat luctus imperdiet. Lorem feugiat dis vehicula laoreet pharetra auctor lorem fames. In torquent conubia curae; hendrerit nisl consequat tempor senectus, luctus ut. Bibendum dapibus porta ante vehicula neque class praesent. Mi consequat. Mauris interdum vestibulum Feugiat cubilia hac dolor lorem egestas neque. Ornare nunc faucibus suscipit nisi justo faucibus porta feugiat per Risus congue curabitur pretium augue nulla. Nec ultricies, mollis. Senectus lectus nonummy malesuada. Nisi neque interdum. Duis condimentum luctus, dapibus.

Sapien consectetuer in parturient mattis pede morbi. Porta sed per at praesent, ullamcorper dolor mauris torquent urna commodo placerat euismod tellus auctor nec malesuada convallis donec accumsan lorem sed rhoncus metus neque aenean vehicula aliquet turpis suscipit sollicitudin tempor facilisis suspendisse euismod hac, sed eget ridiculus ridiculus magna quam. Sodales cursus, natoque habitant lacus tellus vestibulum curae; dui egestas mi rutrum risus condimentum sollicitudin Tortor bibendum fringilla at leo platea cras vivamus vitae ad aenean hac nulla nisl accumsan urna orci. Vestibulum neque, laoreet fusce senectus in magnis morbi porta aenean metus per. Pharetra luctus Facilisi ligula ornare dignissim blandit mus mauris quam eget nunc. Sit elementum aptent sociosqu nullam nam lacinia. Phasellus cubilia Proin. Gravida nibh inceptos per. Donec elit torquent. Dignissim. Habitasse suscipit hendrerit vivamus euismod taciti ut non. A dis egestas arcu varius. Commodo. Commodo, quisque rhoncus hendrerit luctus dis aliquam vestibulum imperdiet cras sollicitudin dictum rutrum lorem volutpat vulputate lacus fames quam sodales. Etiam dignissim aptent Class semper lectus parturient convallis vel ornare nunc Vitae. Ornare luctus. Convallis. Tempus, lectus metus imperdiet nibh nascetur. Risus, bibendum dis posuere vivamus proin congue placerat taciti sociosqu hac justo penatibus parturient libero. Natoque urna tortor class suscipit hendrerit. Sem orci eros nisi auctor, turpis luctus. Nostra interdum varius suscipit. Enim ligula a magna eleifend diam purus posuere odio, ridiculus felis euismod, pharetra habitasse vel blandit congue ornare curae; scelerisque. Taciti torquent porttitor vel faucibus eleifend bibendum integer mus per sapien nostra sollicitudin Mollis a. Consequat interdum at suspendisse, velit dis etiam. Nibh, consequat malesuada scelerisque justo feugiat feugiat tortor habitant bibendum. Nam quam, mattis, ante scelerisque mollis cras integer pretium consequat. Massa vestibulum class eu. Per elit cum orci sapien semper nisl. Consequat elit. Arcu. Dictumst bibendum per. Adipiscing facilisis felis dictum litora aliquet orci nisl posuere mauris natoque cubilia turpis praesent iaculis sed natoque euismod ac consequat fermentum purus risus. Laoreet lorem mi tristique sapien arcu rhoncus praesent urna amet scelerisque primis nibh. Montes cras. Interdum lorem commodo elit erat montes.

Risus montes. Taciti ac proin cras enim. Iaculis elementum taciti metus volutpat. Nullam egestas fermentum natoque erat. Est conubia habitasse hymenaeos aptent. Nec consequat. Eleifend tristique, elementum. Enim curabitur natoque per, lectus quis morbi vivamus placerat hymenaeos proin cum nibh quis. Eros euismod sit curae; enim. Montes integer blandit. Litora viverra. Class hendrerit. Platea. Sagittis hymenaeos. Convallis ligula Justo, mauris duis. Tortor ante eleifend vulputate varius aptent nonummy auctor sociosqu id rutrum posuere imperdiet tempus. Nec massa. Pellentesque ante cursus est metus mattis aliquam magnis faucibus lorem torquent dictum eros diam sem. Leo vivamus facilisi diam per dolor nibh laoreet pretium lorem nulla metus pulvinar nisi convallis suspendisse maecenas sapien varius nascetur lacus aliquet at Maecenas. Etiam. Ridiculus, magna senectus non, nostra. Eros class aliquam congue accumsan. Elit hymenaeos nonummy justo. Natoque eros habitant tempor gravida in eu tristique. Habitant Vestibulum eros eget sollicitudin hymenaeos quisque massa sollicitudin. Feugiat. Iaculis. Varius non massa. Vel potenti morbi ultrices est aptent pretium egestas ligula turpis urna mauris purus pretium purus scelerisque aliquet pretium. Fermentum nunc elit sollicitudin hymenaeos vivamus purus facilisis aliquet euismod. Felis dictumst viverra donec sed fames feugiat diam felis euismod gravida nulla justo vitae platea lobortis sociosqu nisi luctus quis tristique. Felis dictumst mus pede consectetuer montes torquent vestibulum nam potenti tellus eget rhoncus, diam vestibulum. Egestas integer ad ante maecenas inceptos lacinia consectetuer. Dignissim orci vehicula auctor inceptos urna ad. Semper. Nisl morbi odio mollis ridiculus eget.`
];

const key = crypto.randomBytes(32);

(async function () {
  console.log('Samples:', samples.length);
  console.log('The key:', key.toString('hex'));

  for (let i = 0; i < 5; i++) {
    const tests = samples.map((sample) => piscina.run({ data: sample, key }));
    const testResult = await Promise.race(tests);

    for (const key of Object.keys(testResult)) {
      if (testResult[key] instanceof Uint8Array) {
        testResult[key] = Buffer.from(testResult[key]);
      }
    }

    console.log(`Round #${i+1} winner is: ${testResult.decrypted.toString()}\n\n`);
  }
})();
